### ISSUE TITLE
no logging

### ISSUE THREAD

**Issue by prophoto** [thebrandonallen/wp-fail2ban-redux#1]
/var/log/auth.log is empty, ideas? Had the same issue with the original plugin and now your version.

**Comment by thebrandonallen** [comment]
`/var/log/auth.log` is a common log location, especially for Debian/Ubuntu based installs. However, on CentOS (which is was cPanel runs atop), I believe the correct location is `/var/log/secure`. I've also seen `/var/log/messages` being floated around for some setups. You will need to find the correct log location for your server, and replace `/var/log/auth.log` that with that location.

**Comment by prophoto** [comment]
That was it, can you update your docs?
