### ISSUE TITLE
wordpress-hard.conf regex

### ISSUE THREAD

**Issue by ScrewLooseDan** [thebrandonallen/wp-fail2ban-redux#12]
I noticed fail2ban was not banning entries like:

`XML-RPC multicall authentication failure from 1.2.3.4`

When I looked at the regex in wordpress-hard.conf, I see:

`^%(__prefix_line)sXML-RPC multicall authentication failure <HOST>$`

What appears to work for me is:

`^%(__prefix_line)sXML-RPC multicall authentication failure from <HOST>$`

**Comment by thebrandonallen** [comment]
@ScrewLooseDan Thanks for the report. Sorry it took so long to respond.

@acs-ferreira Has submitted a PR for this, which I'm about to merge. I'll aim for a release sometime in the next few days.
