### ISSUE TITLE
Changelog update for 0.6.0

### ISSUE THREAD

**Issue by rumspeed** [thebrandonallen/wp-fail2ban-redux#16]
The changelog entry for 0.6.0 is missing. There is no way to tell what the changes are from the WordPress update methods. The previous version required server changes so it would be good to know if this version needs server adjustments or not.

**Comment by thebrandonallen** [comment]
I'll get that fixed. In the meantime, https://github.com/thebrandonallen/wp-fail2ban-redux/blob/develop/CHANGELOG.md

**Comment by rumspeed** [comment]
Great. Thank you!
