### ISSUE TITLE
user enumeration

### ISSUE THREAD

**Issue by pjv** [thebrandonallen/wp-fail2ban-redux#2]
i'm not (yet) using this plugin, but stumbled onto your repo in researching an issue i just posted for the original wp-fail2ban plugin. quickly looking at your code, i think it should have the same issue, so you might want to take a look at: https://wordpress.org/support/topic/false-positive-on-user-enumeration?replies=1

i'm not sure this is the best solution, but off the top of my head, i think that in the function starting around line 140 in `/classes/class-wp-fail2ban-redux.php` if you check for logged in users and exempted them from the block it would be an improvement.

**Comment by thebrandonallen** [comment]
@pjv Thanks for reporting this, by the way! Sorry it took so long to get back to you.
