### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by HardcoreGames** [thebrandonallen/wp-fail2ban-redux#23]
would be nice to have better WP integration with a settings panel etc

php exec() an call iptables and ban a specific IP address and stuffing the bans into the database seems like a good idea

**Comment by thebrandonallen** [comment]
I think you're misunderstanding how this plugin and Fail2Ban work. This plugin only sends messages to the appropriate event log on the server. Fail2Ban and the configurations settings you choose, via jails and filters, are what determine the items, and the number of the occurrences of those items, cause an IP/host to be added to the server firewall. This plugin only provides events that could be used to block IPs/hosts, but it doesn't choose what/when to block. A settings panel wouldn't provide much utility.
