### ISSUE TITLE
How do I enable the optional filters?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [thebrandonallen/wp-fail2ban-redux#4]
I don't see any documentation for enabling the optional filters.

**Comment by thebrandonallen** [comment]
I think you're looking for this

https://github.com/thebrandonallen/wp-fail2ban-redux/wiki/Filters

**Comment by ahmed-sigmalux** [comment]
Thanks for the link. Somehow I missed that entry in the wiki.

**Comment by thebrandonallen** [comment]
No worries. I should probably get a link in the readme. The existence of the Wiki isn't even obvious if you don't spend a lot of time on GitHub.
