### ISSUE TITLE
Shouldn't $indent be $ident?

### ISSUE THREAD

**Issue by tjcim** [thebrandonallen/wp-fail2ban-redux#7]
Great plugin.  I was trying to figure out the best way to integrate this into a wordpress site run in docker with fail2ban on the docker host, and while doing so have been looking at your code as well as the documentation. I came across this and I am not sure if I just don't understand php enough (totally possible) or it is a misspelling.

You reference $indent and I think it should be $ident as stated in the reference URL you provide https://secure.php.net/manual/en/function.openlog.php - note that if changed, the wiki documentation should be updated as well. 

			/**
			 * Filters the $indent parameter, which will be the `[DAEMON]`
			 * portion of the example in the class PHPDoc, and will be passed to
			 * `openlog()`.
			 *
			 * @see https://secure.php.net/manual/function.openlog.php
			 *
			 * @since 0.1.0
			 *
			 * @param string $indent The syslog tag.
			 * @param string $action The logging action.
			 */
			$indent = apply_filters( 'wp_fail2ban_redux_openlog_indent', "wp({$_SERVER['HTTP_HOST']})", $action );

**Comment by thebrandonallen** [comment]
Yep... Embarrassing

**Comment by tjcim** [comment]
Not at all, you did an awesome job with the code and documentation.... nobody is perfect :)

**Comment by thebrandonallen** [comment]
Gives me a good reason to finally get the `Tested up to` bumped to 4.9 in the readme.
