### ISSUE TITLE
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by einkoro** [thebrandonallen/wp-fail2ban-redux#9]
WP Fail2Ban Redux 0.4.0
WordPress 4.9.8

With WP Fail2Ban Redux enabled the following warning is logged on every request:
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function '_return_true' not found or invalid function name in www/wordpress/wp-includes/class-wp-hook.php on line 286

**Comment by thebrandonallen** [comment]
Are you using any of the filters from the following wiki page? https://github.com/thebrandonallen/wp-fail2ban-redux/wiki/Filters

I had a type in a few of the filter examples that had the callback `__return_true` as `_return_true`. Note that the correct version has two leading underscores, not one.

If you're not using any of these filters, then I couldn't tell you what's happening.

**Comment by einkoro** [comment]
Looks like that was it–thanks.
